apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: chatbot
data:
  LLM_PROVIDER: "ollama"
  OLLAMA_BASE_URL: "http://ollama.chatbot.svc.cluster.local:11434"
  OLLAMA_MODEL: "tinyllama"
  NIM_BASE_URL: ""
  NIM_MODEL: ""
