apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ollama.yaml
  - openwebui-pvc.yaml
  - openwebui-deploy.yaml
  - openwebui-svc.yaml
  - openwebui-ing.yaml

# Remove any chatbot-specific patches
