apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ollama.yaml
patchesStrategicMerge:
- patch-configmap-ollama.yaml
- patch-ingress-host.yaml

resources:
  - openwebui-pvc.yaml
  - openwebui-deploy.yaml
  - openwebui-svc.yaml
  - openwebui-ing.yaml
