apiVersion: v1
kind: Service
metadata:
  name: notes-app
  namespace: notes
  labels:
    app.kubernetes.io/name: notes-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notes-app
  ports:
    - port: 80
      targetPort: 8000
